<?php

namespace Test\FlexiPeeHP\Bricks;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-05-24 at 16:45:31.
 */
class GateKeeperTest extends \Test\Ease\SandTest
{
    /**
     * @var GateKeeper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() : void
    {
        $this->object = new GateKeeper;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() : void
    {
        
    }

    /**
     * @covers FlexiPeeHP\Bricks\GateKeeper::isAccessibleBy
     * @todo   Implement testIsAccessibleBy().
     */
    public function testIsAccessibleBy()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FlexiPeeHP\Bricks\GateKeeper::getDocumentCompany
     * @todo   Implement testGetDocumentCompany().
     */
    public function testGetDocumentCompany()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FlexiPeeHP\Bricks\GateKeeper::getCustomerCompany
     * @todo   Implement testGetCustomerCompany().
     */
    public function testGetCustomerCompany()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
